# model: "THUDM/CogVideoX-5b-I2V"
model: "THUDM/CogVideoX-2b"
# hyper params
gradient_accumulation_steps: 1
batch_size: 1
dataset_size: 5
gradient_clip_val: 1.0
teacher_timesteps: 50
student_timesteps: 1
tmin: 20
tmax: 980
num_epochs: 10
student_gen_train_ratio: 1
guidance_scale: 7.5
generator_one_step_time: 625
height: 480
width: 720
fps: 8
num_frames: 49

generator_lr: 0.00001
student_lr: 0.00001

lora:
    r: 128
    lora_alpha: 64
    target_modules: ["to_q", "to_k", "to_v"]

use_wandb: True
wandb_project: "CogVideoX-SiD-Distillation"
wandb_run_name: "test-6"
wandb_entity: "SiD_pawan"
ckpt_save_path: "checkpoints/"
