model: "Wan-AI/Wan2.1-T2V-1.3B-Diffusers"
# model: "THUDM/CogVideoX-2b"

# training params
num_epochs: 10
gradient_accumulation_steps: 1
batch_size: 1 
dataset_size: 3000
gradient_clip_val: 1.0
generator_lr: 0.00001
fake_score_lr: 0.00001
lora:
    r: 128
    lora_alpha: 64
    target_modules: ["to_q", "to_k", "to_v"]

# SID timestep hparams
generator_timesteps: 1
generator_one_step_time: 1000
tmin: 20
tmax: 800

# other hyperparameters
guidance_scale: 5.0

# video params
height: 480
width: 832
fps: 15
num_frames: 81

# saving/logging
use_wandb: True
wandb_project: "Wan-SiD-Distillation"
wandb_run_name: "debug-1"
wandb_entity: "SiD_pawan"
ckpt_save_path: "checkpoints"
