# pipeline model paths
model: "Wan-AI/Wan2.1-T2V-1.3B-Diffusers"
dit_path: "models/Wan2.1-T2V-1.3B/diffusion_pytorch_model.safetensors"
vae_path: "models/Wan2.1-T2V-1.3B/Wan2.1_VAE.pth"
encoder_path: "models/Wan2.1-T2V-1.3B/models_t5_umt5-xxl-enc-bf16.pth"
# checkpoint_path: "checkpoints/debug-1.ckpt"
# training params
n_devices: 4
num_epochs: 50
gradient_accumulation_steps: 2
batch_size: 1
dataset_size: 200
gradient_clip_val: 1.0
generator_lr: 1e-6
fake_score_lr: 1e-6
lora:
    r: 128
    lora_alpha: 64
    target_modules: ["to_q","to_k","to_v","to_o"]

# SID timestep hparams
generator_timesteps: 1
tmin: 20
tmax: 800

# other hyperparameters
guidance_scale: 5.0
gradient_checkpointing: True
# video params
height: 480
width: 832
fps: 15
num_frames: 81

# saving/logging
use_wandb: True
wandb_project: "Wan-SiD-Distillation"
wandb_run_name: "debug-1"
wandb_entity: "SiD_pawan"
ckpt_directory: "checkpoints"
